[[plugins]]
repo = 'deoplete-plugins/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
hook_add = '''
    let g:deoplete#sources#clang#libclang_path = system("llvm-config --prefix")[:-2] . '/lib/libclang.dylib'
    let g:deoplete#sources#clang#clang_header = system("llvm-config --prefix")[:-2] . '/lib/clang'
    let g:deoplete#sources#clang#sort_algo = 'priority'
    let g:deoplete#sources#clang#clang_complete_database = "./build/"
'''
depends = ['deoplete.nvim']

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp']
hook_add = '''
  let g:clang_format#auto_format = 1
  let g:clang_format#style_options = {
    \ "ColumnLimit": 120,
    \ "IndentWidth": 4,
    \ "Standard": "C++11",
    \ "AccessModifierOffset": -4,
    \ "IndentCaseLabels": "false",
    \ "AlignAfterOpenBracket": "Align",
    \ "AlignConsecutiveAssignments": "false",
    \ "AlignTrailingComments": "true",
    \ "AlignOperands": "true",
    \ "AllowShortBlocksOnASingleLine": "false",
    \ "BinPackArguments": "true",
    \ "Cpp11BracedListStyle": "false",
    \ "DerivePointerAlignment": "false",
    \ "PointerAlignment": "Right",
    \ "ReflowComments": "false",
    \ "SortIncludes": "false",
    \ "BreakConstructorInitializers": "BeforeColon",
    \ "ConstructorInitializerAllOnOneLineOrOnePerLine": "true"}
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

