[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vim-devicons', 'vim-nerdtree-syntax-highlight', 'nerdtree-git-plugin']
hook_add = '''
  nnoremap <silent><C-\> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ['python']
build = './install_gadget.py --enable-python'
hook_add = '''
  nmap <A-5>    <Plug>VimspectorContinue
  nmap <A-3>    <Plug>VimspectorStop
  nmap <A-4>    <Plug>VimspectorPause
  nmap <A-6>    <Plug>VimspectorRestert
  nmap <A-9>    <Plug>VimspectorToggleBreakpoint
  nmap <A-0>    <Plug>VimspectorStepOver
  nmap <A-1>    <Plug>VimspectorStepInto
  nmap <A-2>    <Plug>VimspectorStepOut
'''

